# Excercise
1. Generate a 1-D array containing 5 random integers from 0 to 100:
2. Generate a 2-D array with 3 rows, each row contains 5 random integers from 0 to 100
3. Generate a 1-D array of 30 evenly spaced elements between 1.5 and 5.5, inclusive.

In [2]:
import numpy as np
from numpy import random

In [3]:
#No 1

a = random.randint(0, 100, size=(1,5))
a

array([[24, 63,  1, 96, 45]])

In [4]:
#No 2

a = random.randint(0, 100, size=(3,5))
a

array([[42, 70, 41,  6, 85],
       [63, 22, 32, 13, 69],
       [14, 94, 47, 85, 53]])

In [5]:
#No 3

a = np.linspace(1.5, 5.5, 30)
a

array([1.5       , 1.63793103, 1.77586207, 1.9137931 , 2.05172414,
       2.18965517, 2.32758621, 2.46551724, 2.60344828, 2.74137931,
       2.87931034, 3.01724138, 3.15517241, 3.29310345, 3.43103448,
       3.56896552, 3.70689655, 3.84482759, 3.98275862, 4.12068966,
       4.25862069, 4.39655172, 4.53448276, 4.67241379, 4.81034483,
       4.94827586, 5.0862069 , 5.22413793, 5.36206897, 5.5       ])