# NUMPY

In [9]:
import numpy as np

In [11]:
# python list
a = [1, 2, 3, 4]
b = [5, 6, 7, 8]

In [12]:
print(a+b)
print(a*b)

[1, 2, 3, 4, 5, 6, 7, 8]


TypeError: ignored

In [14]:
a_array = np.array(a)
b_array = np.array(b)

print(a_array + b_array)
print(a_array * b_array)

[ 6  8 10 12]
[ 5 12 21 32]


In [15]:
# one dimensional array
x = np.array([1, 2, 3, 4, 5])
x

array([1, 2, 3, 4, 5])

In [16]:
x.shape

(5,)

In [20]:
# two dimensional array
y = np.array([[1,2,3],
              [4,5,6],
              [7, 8, 9]])
y.shape

(3, 3)

In [21]:
y.size

9

In [22]:
type(y)

numpy.ndarray

In [23]:
a = [1, 2, 3]
type(a)

list

In [25]:
# three dimensional array
z = np.array([[[1,2,3,4,5],
               [6,7,8,8,10],
               [11,12,13,14,15]],
             [[1,2,3,4,5],
              [6,7,8,9,10],
             [11,12,13,14,15]],
             [[1,2,3,4,5],
              [6,7,8,9,10],
             [11,12,13,14,15]],
              [[1,2,3,4,5],
               [6,7,8,9,10],
               [11,12,13,14,15]]])
z.shape

(4, 3, 5)

In [29]:
# Matrix zeros
zeros_matrix = np.zeros(5)
zeros_matrix

array([0., 0., 0., 0., 0.])

In [31]:
zeros_matrix2 = np.zeros((5,2))
zeros_matrix2

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [32]:
zeros_matrix3 = np.zeros((2,3,4))
zeros_matrix3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [34]:
# matrix ones
ones_matrix = np.ones(5)
ones_matrix

array([1., 1., 1., 1., 1.])

In [36]:
one_matrix3 = np.ones((1,2,3))
one_matrix3

array([[[1., 1., 1.],
        [1., 1., 1.]]])

In [38]:
# arrange
x = np.arange(10) # start=0, stop=10, step=1
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
y = np.arange(10,20) # start=10, stop=20, step=1
y

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [40]:
z = np.arange(10,20,2) #start=10, stop=20, step=2
z

array([10, 12, 14, 16, 18])

In [48]:
# linspace
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [52]:
# random
from numpy import random

random.rand(4,5,3)

array([[[0.2721758 , 0.17542391, 0.1000995 ],
        [0.23322326, 0.17710606, 0.57588582],
        [0.8700896 , 0.90172591, 0.00164897],
        [0.12378088, 0.5391974 , 0.3018374 ],
        [0.66743768, 0.82512119, 0.66731815]],

       [[0.15365309, 0.52026563, 0.06481801],
        [0.61356953, 0.26157162, 0.83924277],
        [0.26556469, 0.81686949, 0.66933897],
        [0.63307737, 0.16160696, 0.35194079],
        [0.48602908, 0.2131611 , 0.77722493]],

       [[0.74135781, 0.77876871, 0.95280796],
        [0.6795722 , 0.08466339, 0.81251816],
        [0.09890593, 0.38383687, 0.39041939],
        [0.79858891, 0.38965938, 0.54474031],
        [0.87305421, 0.9464015 , 0.02733208]],

       [[0.91125209, 0.69689624, 0.68983136],
        [0.21192183, 0.46647153, 0.42017393],
        [0.54460159, 0.71770262, 0.31984106],
        [0.30280612, 0.9533439 , 0.78347756],
        [0.32243435, 0.39301888, 0.34790799]]])

In [56]:
# random integer
random.randint(2, 10, size=(4,5))

array([[2, 4, 8, 9, 7],
       [3, 5, 6, 7, 6],
       [8, 5, 3, 4, 9],
       [9, 6, 3, 9, 6]])

# Excercise
1. Generate a 1-D array containing 5 random integers from 0 to 100:
2. Generate a 2-D array with 3 rows, each row contains 5 random integers from 0 to 100
3. Generate a 1-D array of 30 evenly spaced elements between 1.5 and 5.5, inclusive.