In [1]:
import numpy as np

In [2]:
# append
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr = np.append(arr, (10, 11, 12))
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [6]:
arr2 = np.array([[1,2,3],
                 [4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr2 = np.append(arr2, [[7,8,9]], axis=0)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr2 = np.append(arr2, [[1,1,1]], axis=0)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 1, 1]])

In [11]:
arr2 = np.append(arr2, [[0], [0], [0], [0]], axis=1)
arr2

array([[1, 2, 3, 0],
       [4, 5, 6, 0],
       [7, 8, 9, 0],
       [1, 1, 1, 0]])

In [14]:
arr2 = np.append(arr2, [[1,2,3,4]], axis=0)
arr2

array([[1, 2, 3, 0],
       [4, 5, 6, 0],
       [7, 8, 9, 0],
       [1, 1, 1, 0],
       [1, 2, 3, 4]])

In [16]:
# concate
arr_a = np.array([[1,2,3],
                  [4,5,6]])
arr_b = np.array([[7,8,9],
                  [10,11,12]])

arr_c = np.concatenate((arr_a, arr_b), axis=0)
arr_c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [20]:
arr_d = np.array([[1,2,3],
                  [4,5,6]])
arr_e = np.array([[7,8,9],
                  [10,11,12]])

arr_f = np.concatenate((arr_d, arr_e), axis=1)
arr_f

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [21]:
# sorting in numpy
from numpy import random
arr = random.randint(1,10, size=(10,))
arr

array([2, 6, 9, 9, 5, 1, 7, 6, 4, 6])

In [22]:
np.sort(arr)

array([1, 2, 4, 5, 6, 6, 6, 7, 9, 9])

In [23]:
np.sort(arr)[::-1]

array([9, 9, 7, 6, 6, 6, 5, 4, 2, 1])

In [26]:
# delete
arr = np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
np.delete(arr, 1, axis=0)

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [28]:
np.delete(arr, 2, axis=1)

array([[ 1,  2,  4],
       [ 5,  6,  8],
       [ 9, 10, 12]])

In [29]:
# shape, size, dim
arr3 = random.randint(1,10, size=(3,3,3))
arr3

array([[[3, 2, 1],
        [7, 4, 3],
        [4, 6, 2]],

       [[8, 6, 3],
        [5, 1, 7],
        [2, 9, 8]],

       [[7, 3, 4],
        [3, 8, 8],
        [5, 5, 8]]])

In [30]:
arr3.ndim

3

In [31]:
arr3.shape

(3, 3, 3)

In [32]:
arr3.size

27

In [42]:
# reshape
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
a.shape

(10,)

In [44]:
a[4]

4

In [41]:
a.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [43]:
#expand dim
a_dim = np.expand_dims(a, axis=1)
a_dim

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [46]:
a_dim[4,0]

4

In [48]:
a_dim.shape

(10, 1)

In [51]:
# accessing item
arr = random.randint(1,10, size=(5))
arr

array([2, 1, 7, 3, 8])

In [53]:
arr[4]

8

In [54]:
arr[:4]

array([2, 1, 7, 3])

In [56]:
arr[3:]

array([3, 8])

In [57]:
arr[-1]

8

In [58]:
arr[-5]

2

In [59]:
arr[-8]

IndexError: ignored

In [61]:
arr = random.randint(1,100, size=20)
arr

array([15, 97, 82, 45, 50, 99, 22,  6, 39, 67, 23, 28, 21, 42, 18, 11, 16,
       88, 60, 10])

In [62]:
# selecting
arr[arr>45]

array([97, 82, 50, 99, 67, 88, 60])

In [63]:
arr[arr % 2 == 0]

array([82, 50, 22,  6, 28, 42, 18, 16, 88, 60, 10])

In [67]:
arr[(arr % 2 == 0) | (arr % 3 == 0)]

array([15, 82, 45, 50, 99, 22,  6, 39, 28, 21, 42, 18, 16, 88, 60, 10])

In [76]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [74]:
# vstack
np.vstack((a1,a2)) # pastikan axis 1 itu harus sama

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5]])

In [77]:
# hstack
np.hstack((a1,a2)) # pastikan axis 0 nya sama

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [80]:
# array operation

a = np.array([1,2,3,4,5])
a.sum()

15

In [87]:
a[a.argmax()]

5

In [88]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [89]:
dir = '/content/drive/MyDrive/intermediate-python'

In [90]:
# save and load numpy
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [92]:
import os
np.save(os.path.join(dir, "myfile"), a)

In [94]:
arr = np.load(os.path.join(dir, "myfile.npy"))
arr

array([1, 2, 3, 4, 5, 6])

In [95]:
csv_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.savetxt('/content/drive/MyDrive/intermediate-python/myfile2.csv', csv_arr)

In [96]:
np.loadtxt('/content/drive/MyDrive/intermediate-python/myfile2.csv')

array([1., 2., 3., 4., 5., 6., 7., 8.])

# Assingment
1. Create a 4x4 matrix with values ranging from 0 to 3.
2. Create an array with shape of 4x4 and turn it into two arrays along the second axis.